// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJNQu3KXkiiPaZN1U7mruz11rKE4YeRE',
    appId: '1:718724382718:web:26a9385cd900660d934aaf',
    messagingSenderId: '718724382718',
    projectId: 'aplication-1-2aa81',
    authDomain: 'aplication-1-2aa81.firebaseapp.com',
    storageBucket: 'aplication-1-2aa81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLkLaOir95BcoGaGroFUe8SxrgmKMmrlw',
    appId: '1:718724382718:android:8ff695feb6c8f816934aaf',
    messagingSenderId: '718724382718',
    projectId: 'aplication-1-2aa81',
    storageBucket: 'aplication-1-2aa81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAar_O_3LJ5BRXQQwo12jFu_kKVWKtwOTE',
    appId: '1:718724382718:ios:ab83a19793a3383e934aaf',
    messagingSenderId: '718724382718',
    projectId: 'aplication-1-2aa81',
    storageBucket: 'aplication-1-2aa81.appspot.com',
    iosClientId: '718724382718-55avdtrh4c8d7di0ql3rnqdminlrutl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.thiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAar_O_3LJ5BRXQQwo12jFu_kKVWKtwOTE',
    appId: '1:718724382718:ios:ab83a19793a3383e934aaf',
    messagingSenderId: '718724382718',
    projectId: 'aplication-1-2aa81',
    storageBucket: 'aplication-1-2aa81.appspot.com',
    iosClientId: '718724382718-55avdtrh4c8d7di0ql3rnqdminlrutl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.thiktokClone',
  );
}
